/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/garments/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Analyze a garment image and extract structured traits.
         * @description Stateless — sends the image to a vision model and returns extracted traits.
         *     No authentication required. No data is persisted.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["AnalyzeRequest"];
                    "text/json": components["schemas"]["AnalyzeRequest"];
                    "application/*+json": components["schemas"]["AnalyzeRequest"];
                };
            };
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AnalyzeResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Client Error */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Server Error */
                502: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/garments/analyze-batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Analyze multiple garment images and extract per-person clothing traits from each.
         * @description Stateless. Sends all images to the vision model in one call and returns structured
         *     traits per person per image. Captures multi-person outfits that /analyze cannot.
         *     No authentication required. No data is persisted.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["BatchAnalyzeRequest"];
                    "text/json": components["schemas"]["BatchAnalyzeRequest"];
                    "application/*+json": components["schemas"]["BatchAnalyzeRequest"];
                };
            };
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BatchAnalyzeResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Server Error */
                502: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/garments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the current user's garments with optional category filter and paging. */
        get: {
            parameters: {
                query?: {
                    category?: components["schemas"]["GarmentCategory"];
                    page?: number;
                    pageSize?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["GarmentListResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        /** Store a new garment with its image and extracted traits. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CreateGarmentRequest"];
                    "text/json": components["schemas"]["CreateGarmentRequest"];
                    "application/*+json": components["schemas"]["CreateGarmentRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["GarmentResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/garments/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a single garment by ID (must belong to the current user). */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["GarmentResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        /** Delete a garment and its stored image (must belong to the current user). */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Simple liveness check — returns 200 if the API is running. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Return the current user's identity derived from the validated JWT. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MeResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/me/profile/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate or refresh the current user's style profile from their wardrobe. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProfileResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/me/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the current user's last generated style profile. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProfileResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/me/recommendations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get ranked recommendations based on the user's style profile and inventory.
         * @description Requires a generated style profile. Returns items ranked by fit score,
         *     filtered by optional budget, category, and occasion constraints.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["RecommendRequest"];
                    "text/json": components["schemas"]["RecommendRequest"];
                    "application/*+json": components["schemas"]["RecommendRequest"];
                };
            };
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RecommendationsResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AnalyzeRequest: {
            imageBase64?: string | null;
            mimeType?: string | null;
        };
        AnalyzeResponse: {
            traits?: components["schemas"]["GarmentTraits"];
            modelVersion?: string | null;
        };
        BatchAnalyzeImageRequest: {
            imageId?: string | null;
            imageBase64?: string | null;
            mimeType?: string | null;
        };
        BatchAnalyzeRequest: {
            images?: components["schemas"]["BatchAnalyzeImageRequest"][] | null;
        };
        BatchAnalyzeResponse: {
            images?: components["schemas"]["ImageTraitsResult"][] | null;
            modelVersion?: string | null;
        };
        BoundingBox: {
            /** Format: double */
            x?: number;
            /** Format: double */
            y?: number;
            /** Format: double */
            width?: number;
            /** Format: double */
            height?: number;
        };
        ClothingItemTraits: {
            category?: string | null;
            type?: string | null;
            subtype?: string | null;
            primaryColor?: components["schemas"]["ColorTraits"];
            secondaryColors?: components["schemas"]["ColorTraits"][] | null;
            pattern?: string | null;
            material?: string | null;
            fit?: string | null;
            length?: string | null;
            sleeveLength?: string | null;
            neckline?: string | null;
            collarType?: string | null;
            waistRise?: string | null;
            closureType?: string | null;
            details?: string[] | null;
            visibleText?: string | null;
            brand?: string | null;
            logo?: string | null;
            condition?: string | null;
            styleTags?: string[] | null;
            /** Format: double */
            confidence?: number;
            boundingBox?: components["schemas"]["BoundingBox"];
        };
        ColorInfo: {
            name?: string | null;
            hex?: string | null;
        };
        ColorTraits: {
            normalized?: string | null;
            shade?: string | null;
        };
        ColorWeight: {
            name?: string | null;
            hex?: string | null;
            /** Format: double */
            weight?: number;
        };
        CreateGarmentRequest: {
            traits?: components["schemas"]["GarmentTraits"];
            imageBase64?: string | null;
            mimeType?: string | null;
        };
        ErrorResponse: {
            error?: string | null;
            detail?: string | null;
        };
        FormalityRange: {
            /** Format: int32 */
            min?: number;
            /** Format: int32 */
            max?: number;
            /** Format: double */
            typical?: number;
        };
        /** @enum {string} */
        GarmentCategory: "top" | "bottom" | "dress" | "outerwear" | "footwear" | "accessory" | "other";
        /** @enum {string} */
        GarmentFit: "slim" | "regular" | "loose" | "oversized";
        GarmentListResponse: {
            items?: components["schemas"]["GarmentResponse"][] | null;
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            pageSize?: number;
        };
        /** @enum {string} */
        GarmentPattern: "solid" | "striped" | "plaid" | "checked" | "floral" | "graphic" | "other";
        GarmentResponse: {
            id?: string | null;
            userId?: string | null;
            traits?: components["schemas"]["GarmentTraits"];
            imageUrl?: string | null;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            modifiedAt?: string;
            createdByUserId?: string | null;
            modifiedByUserId?: string | null;
        };
        GarmentTraits: {
            category?: components["schemas"]["GarmentCategory"];
            subcategory?: string | null;
            primaryColor?: components["schemas"]["ColorInfo"];
            secondaryColors?: components["schemas"]["ColorInfo"][] | null;
            pattern?: components["schemas"]["GarmentPattern"];
            material?: string | null;
            fit?: components["schemas"]["GarmentFit"];
            /** Format: int32 */
            formality?: number;
            seasonality?: components["schemas"]["Season"][] | null;
            styleTags?: string[] | null;
            occasions?: string[] | null;
            /** Format: double */
            confidence?: number;
        };
        ImageTraitsResult: {
            imageId?: string | null;
            people?: components["schemas"]["PersonTraits"][] | null;
            warnings?: string[] | null;
        };
        InventoryItem: {
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            modifiedAt?: string;
            createdByUserId?: string | null;
            modifiedByUserId?: string | null;
            id?: string | null;
            vendorId?: string | null;
            name?: string | null;
            description?: string | null;
            traits?: components["schemas"]["GarmentTraits"];
            /** Format: double */
            price?: number;
            currency?: string | null;
            url?: string | null;
            imageUrl?: string | null;
            inStock?: boolean;
        };
        MeResponse: {
            userId?: string | null;
            name?: string | null;
            provider?: string | null;
        };
        PersonTraits: {
            personId?: string | null;
            position?: string | null;
            overallStyle?: string[] | null;
            styleTags?: string[] | null;
            clothingItems?: components["schemas"]["ClothingItemTraits"][] | null;
            /** Format: double */
            overallConfidence?: number;
            faceBoundingBox?: components["schemas"]["BoundingBox"];
        };
        ProblemDetails: {
            type?: string | null;
            title?: string | null;
            /** Format: int32 */
            status?: number | null;
            detail?: string | null;
            instance?: string | null;
        } & {
            [key: string]: unknown;
        };
        ProfileResponse: {
            dominantStyles?: string[] | null;
            colorPalette?: components["schemas"]["ColorWeight"][] | null;
            formalityRange?: components["schemas"]["FormalityRange"];
            preferredFits?: string[] | null;
            seasonalSkew?: {
                [key: string]: number;
            } | null;
            summary?: string | null;
            /** Format: int32 */
            garmentCount?: number;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            modifiedAt?: string;
            createdByUserId?: string | null;
            modifiedByUserId?: string | null;
        };
        RecommendRequest: {
            /** Format: double */
            maxBudget?: number | null;
            currency?: string | null;
            categories?: components["schemas"]["GarmentCategory"][] | null;
            occasion?: string | null;
            /** Format: int32 */
            count?: number;
        };
        Recommendation: {
            inventoryItem?: components["schemas"]["InventoryItem"];
            /** Format: double */
            score?: number;
            reasoning?: string | null;
        };
        RecommendationsResponse: {
            recommendations?: components["schemas"]["Recommendation"][] | null;
            /** Format: date-time */
            profileGeneratedAt?: string;
            /** Format: date-time */
            requestedAt?: string;
        };
        /** @enum {string} */
        Season: "spring" | "summer" | "fall" | "winter" | "all";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
