<Project>
  <PropertyGroup>
    <!-- Redirect build outputs to a central absolute folder. -->
    <OutDir>..\..\..\project-outputs\robe.ai\$(MSBuildProjectName)\$(Configuration)\</OutDir>
    <!-- Optional: control publish output folder as well. -->
    <PublishDir>..\..\..\project-outputs\robe.ai\$(MSBuildProjectName)\publish\</PublishDir>
  </PropertyGroup>
</Project>
