<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Robe.Infrastructure</RootNamespace>
    <AssemblyName>Robe.Infrastructure</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Azure.AI.OpenAI" Version="2.1.0" />
    <PackageReference Include="Microsoft.ApplicationInsights" Version="2.22.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\robe.core\robe.core.csproj" />
  </ItemGroup>

</Project>
