/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Robe.AI — Wardrobe Style API
 * Garment trait extraction, wardrobe management, style profiling, and recommendations.
 * OpenAPI spec version: v1
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  AnalyzeRequest,
  AnalyzeResponse,
  BatchAnalyzeRequest,
  BatchAnalyzeResponse,
  CreateGarmentRequest,
  ErrorResponse,
  GarmentListResponse,
  GarmentResponse,
  GetApiGarmentsParams,
  ProblemDetails
} from '../generated-client.schemas';


type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;




/**
 * Stateless — sends the image to a vision model and returns extracted traits.
No authentication required. No data is persisted.
 * @summary Analyze a garment image and extract structured traits.
 */
export const postApiGarmentsAnalyze = (
    analyzeRequest: AnalyzeRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<AnalyzeResponse>> => {
    
    
    return axios.post(
      `/api/garments/analyze`,
      analyzeRequest,options
    );
  }



export const getPostApiGarmentsAnalyzeMutationOptions = <TError = AxiosError<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiGarmentsAnalyze>>, TError,{data: AnalyzeRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof postApiGarmentsAnalyze>>, TError,{data: AnalyzeRequest}, TContext> => {

const mutationKey = ['postApiGarmentsAnalyze'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiGarmentsAnalyze>>, {data: AnalyzeRequest}> = (props) => {
          const {data} = props ?? {};

          return  postApiGarmentsAnalyze(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiGarmentsAnalyzeMutationResult = NonNullable<Awaited<ReturnType<typeof postApiGarmentsAnalyze>>>
    export type PostApiGarmentsAnalyzeMutationBody = AnalyzeRequest
    export type PostApiGarmentsAnalyzeMutationError = AxiosError<ErrorResponse>

    /**
 * @summary Analyze a garment image and extract structured traits.
 */
export const usePostApiGarmentsAnalyze = <TError = AxiosError<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiGarmentsAnalyze>>, TError,{data: AnalyzeRequest}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiGarmentsAnalyze>>,
        TError,
        {data: AnalyzeRequest},
        TContext
      > => {

      const mutationOptions = getPostApiGarmentsAnalyzeMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Stateless. Sends all images to the vision model in one call and returns structured
traits per person per image. Captures multi-person outfits that /analyze cannot.
No authentication required. No data is persisted.
 * @summary Analyze multiple garment images and extract per-person clothing traits from each.
 */
export const postApiGarmentsAnalyzeBatch = (
    batchAnalyzeRequest: BatchAnalyzeRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<BatchAnalyzeResponse>> => {
    
    
    return axios.post(
      `/api/garments/analyze-batch`,
      batchAnalyzeRequest,options
    );
  }



export const getPostApiGarmentsAnalyzeBatchMutationOptions = <TError = AxiosError<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiGarmentsAnalyzeBatch>>, TError,{data: BatchAnalyzeRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof postApiGarmentsAnalyzeBatch>>, TError,{data: BatchAnalyzeRequest}, TContext> => {

const mutationKey = ['postApiGarmentsAnalyzeBatch'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiGarmentsAnalyzeBatch>>, {data: BatchAnalyzeRequest}> = (props) => {
          const {data} = props ?? {};

          return  postApiGarmentsAnalyzeBatch(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiGarmentsAnalyzeBatchMutationResult = NonNullable<Awaited<ReturnType<typeof postApiGarmentsAnalyzeBatch>>>
    export type PostApiGarmentsAnalyzeBatchMutationBody = BatchAnalyzeRequest
    export type PostApiGarmentsAnalyzeBatchMutationError = AxiosError<ErrorResponse>

    /**
 * @summary Analyze multiple garment images and extract per-person clothing traits from each.
 */
export const usePostApiGarmentsAnalyzeBatch = <TError = AxiosError<ErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiGarmentsAnalyzeBatch>>, TError,{data: BatchAnalyzeRequest}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiGarmentsAnalyzeBatch>>,
        TError,
        {data: BatchAnalyzeRequest},
        TContext
      > => {

      const mutationOptions = getPostApiGarmentsAnalyzeBatchMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Store a new garment with its image and extracted traits.
 */
export const postApiGarments = (
    createGarmentRequest: CreateGarmentRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<GarmentResponse>> => {
    
    
    return axios.post(
      `/api/garments`,
      createGarmentRequest,options
    );
  }



export const getPostApiGarmentsMutationOptions = <TError = AxiosError<ErrorResponse | ProblemDetails>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiGarments>>, TError,{data: CreateGarmentRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof postApiGarments>>, TError,{data: CreateGarmentRequest}, TContext> => {

const mutationKey = ['postApiGarments'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiGarments>>, {data: CreateGarmentRequest}> = (props) => {
          const {data} = props ?? {};

          return  postApiGarments(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiGarmentsMutationResult = NonNullable<Awaited<ReturnType<typeof postApiGarments>>>
    export type PostApiGarmentsMutationBody = CreateGarmentRequest
    export type PostApiGarmentsMutationError = AxiosError<ErrorResponse | ProblemDetails>

    /**
 * @summary Store a new garment with its image and extracted traits.
 */
export const usePostApiGarments = <TError = AxiosError<ErrorResponse | ProblemDetails>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiGarments>>, TError,{data: CreateGarmentRequest}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiGarments>>,
        TError,
        {data: CreateGarmentRequest},
        TContext
      > => {

      const mutationOptions = getPostApiGarmentsMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary List the current user's garments with optional category filter and paging.
 */
export const getApiGarments = (
    params?: GetApiGarmentsParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<GarmentListResponse>> => {
    
    
    return axios.get(
      `/api/garments`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }




export const getGetApiGarmentsQueryKey = (params?: GetApiGarmentsParams,) => {
    return [
    `/api/garments`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetApiGarmentsQueryOptions = <TData = Awaited<ReturnType<typeof getApiGarments>>, TError = AxiosError<ProblemDetails>>(params?: GetApiGarmentsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiGarments>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiGarmentsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiGarments>>> = ({ signal }) => getApiGarments(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiGarments>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetApiGarmentsQueryResult = NonNullable<Awaited<ReturnType<typeof getApiGarments>>>
export type GetApiGarmentsQueryError = AxiosError<ProblemDetails>


export function useGetApiGarments<TData = Awaited<ReturnType<typeof getApiGarments>>, TError = AxiosError<ProblemDetails>>(
 params: undefined |  GetApiGarmentsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiGarments>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiGarments>>,
          TError,
          Awaited<ReturnType<typeof getApiGarments>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetApiGarments<TData = Awaited<ReturnType<typeof getApiGarments>>, TError = AxiosError<ProblemDetails>>(
 params?: GetApiGarmentsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiGarments>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiGarments>>,
          TError,
          Awaited<ReturnType<typeof getApiGarments>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetApiGarments<TData = Awaited<ReturnType<typeof getApiGarments>>, TError = AxiosError<ProblemDetails>>(
 params?: GetApiGarmentsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiGarments>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary List the current user's garments with optional category filter and paging.
 */

export function useGetApiGarments<TData = Awaited<ReturnType<typeof getApiGarments>>, TError = AxiosError<ProblemDetails>>(
 params?: GetApiGarmentsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiGarments>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetApiGarmentsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Get a single garment by ID (must belong to the current user).
 */
export const getApiGarmentsId = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<GarmentResponse>> => {
    
    
    return axios.get(
      `/api/garments/${id}`,options
    );
  }




export const getGetApiGarmentsIdQueryKey = (id?: string,) => {
    return [
    `/api/garments/${id}`
    ] as const;
    }

    
export const getGetApiGarmentsIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiGarmentsId>>, TError = AxiosError<ProblemDetails>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiGarmentsId>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiGarmentsIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiGarmentsId>>> = ({ signal }) => getApiGarmentsId(id, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiGarmentsId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetApiGarmentsIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiGarmentsId>>>
export type GetApiGarmentsIdQueryError = AxiosError<ProblemDetails>


export function useGetApiGarmentsId<TData = Awaited<ReturnType<typeof getApiGarmentsId>>, TError = AxiosError<ProblemDetails>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiGarmentsId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiGarmentsId>>,
          TError,
          Awaited<ReturnType<typeof getApiGarmentsId>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetApiGarmentsId<TData = Awaited<ReturnType<typeof getApiGarmentsId>>, TError = AxiosError<ProblemDetails>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiGarmentsId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiGarmentsId>>,
          TError,
          Awaited<ReturnType<typeof getApiGarmentsId>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetApiGarmentsId<TData = Awaited<ReturnType<typeof getApiGarmentsId>>, TError = AxiosError<ProblemDetails>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiGarmentsId>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary Get a single garment by ID (must belong to the current user).
 */

export function useGetApiGarmentsId<TData = Awaited<ReturnType<typeof getApiGarmentsId>>, TError = AxiosError<ProblemDetails>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiGarmentsId>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetApiGarmentsIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Delete a garment and its stored image (must belong to the current user).
 */
export const deleteApiGarmentsId = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.delete(
      `/api/garments/${id}`,options
    );
  }



export const getDeleteApiGarmentsIdMutationOptions = <TError = AxiosError<ProblemDetails>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiGarmentsId>>, TError,{id: string}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof deleteApiGarmentsId>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteApiGarmentsId'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiGarmentsId>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteApiGarmentsId(id,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteApiGarmentsIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiGarmentsId>>>
    
    export type DeleteApiGarmentsIdMutationError = AxiosError<ProblemDetails>

    /**
 * @summary Delete a garment and its stored image (must belong to the current user).
 */
export const useDeleteApiGarmentsId = <TError = AxiosError<ProblemDetails>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiGarmentsId>>, TError,{id: string}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteApiGarmentsId>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getDeleteApiGarmentsIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    