/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Robe.AI — Wardrobe Style API
 * Garment trait extraction, wardrobe management, style profiling, and recommendations.
 * OpenAPI spec version: v1
 */
export interface AnalyzeRequest {
  /** @nullable */
  imageBase64?: string | null;
  /** @nullable */
  mimeType?: string | null;
}

export interface AnalyzeResponse {
  traits?: GarmentTraits;
  /** @nullable */
  modelVersion?: string | null;
}

export interface BatchAnalyzeImageRequest {
  /** @nullable */
  imageId?: string | null;
  /** @nullable */
  imageBase64?: string | null;
  /** @nullable */
  mimeType?: string | null;
}

export interface BatchAnalyzeRequest {
  /** @nullable */
  images?: BatchAnalyzeImageRequest[] | null;
}

export interface BatchAnalyzeResponse {
  /** @nullable */
  images?: ImageTraitsResult[] | null;
  /** @nullable */
  modelVersion?: string | null;
}

export interface BoundingBox {
  x?: number;
  y?: number;
  width?: number;
  height?: number;
}

export interface ClothingItemTraits {
  /** @nullable */
  category?: string | null;
  /** @nullable */
  type?: string | null;
  /** @nullable */
  subtype?: string | null;
  primaryColor?: ColorTraits;
  /** @nullable */
  secondaryColors?: ColorTraits[] | null;
  /** @nullable */
  pattern?: string | null;
  /** @nullable */
  material?: string | null;
  /** @nullable */
  fit?: string | null;
  /** @nullable */
  length?: string | null;
  /** @nullable */
  sleeveLength?: string | null;
  /** @nullable */
  neckline?: string | null;
  /** @nullable */
  collarType?: string | null;
  /** @nullable */
  waistRise?: string | null;
  /** @nullable */
  closureType?: string | null;
  /** @nullable */
  details?: string[] | null;
  /** @nullable */
  visibleText?: string | null;
  /** @nullable */
  brand?: string | null;
  /** @nullable */
  logo?: string | null;
  /** @nullable */
  condition?: string | null;
  /** @nullable */
  styleTags?: string[] | null;
  confidence?: number;
  boundingBox?: BoundingBox;
}

export interface ColorInfo {
  /** @nullable */
  name?: string | null;
  /** @nullable */
  hex?: string | null;
}

export interface ColorTraits {
  /** @nullable */
  normalized?: string | null;
  /** @nullable */
  shade?: string | null;
}

export interface ColorWeight {
  /** @nullable */
  name?: string | null;
  /** @nullable */
  hex?: string | null;
  weight?: number;
}

export interface CreateGarmentRequest {
  traits?: GarmentTraits;
  /** @nullable */
  imageBase64?: string | null;
  /** @nullable */
  mimeType?: string | null;
}

export interface ErrorResponse {
  /** @nullable */
  error?: string | null;
  /** @nullable */
  detail?: string | null;
}

export interface FormalityRange {
  min?: number;
  max?: number;
  typical?: number;
}

export type GarmentCategory = typeof GarmentCategory[keyof typeof GarmentCategory];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GarmentCategory = {
  top: 'top',
  bottom: 'bottom',
  dress: 'dress',
  outerwear: 'outerwear',
  footwear: 'footwear',
  accessory: 'accessory',
  other: 'other',
} as const;

export type GarmentFit = typeof GarmentFit[keyof typeof GarmentFit];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GarmentFit = {
  slim: 'slim',
  regular: 'regular',
  loose: 'loose',
  oversized: 'oversized',
} as const;

export interface GarmentListResponse {
  /** @nullable */
  items?: GarmentResponse[] | null;
  page?: number;
  pageSize?: number;
}

export type GarmentPattern = typeof GarmentPattern[keyof typeof GarmentPattern];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GarmentPattern = {
  solid: 'solid',
  striped: 'striped',
  plaid: 'plaid',
  checked: 'checked',
  floral: 'floral',
  graphic: 'graphic',
  other: 'other',
} as const;

export interface GarmentResponse {
  /** @nullable */
  id?: string | null;
  /** @nullable */
  userId?: string | null;
  traits?: GarmentTraits;
  /** @nullable */
  imageUrl?: string | null;
  createdAt?: string;
  modifiedAt?: string;
  /** @nullable */
  createdByUserId?: string | null;
  /** @nullable */
  modifiedByUserId?: string | null;
}

export interface GarmentTraits {
  category?: GarmentCategory;
  /** @nullable */
  subcategory?: string | null;
  primaryColor?: ColorInfo;
  /** @nullable */
  secondaryColors?: ColorInfo[] | null;
  pattern?: GarmentPattern;
  /** @nullable */
  material?: string | null;
  fit?: GarmentFit;
  formality?: number;
  /** @nullable */
  seasonality?: Season[] | null;
  /** @nullable */
  styleTags?: string[] | null;
  /** @nullable */
  occasions?: string[] | null;
  confidence?: number;
}

export interface ImageTraitsResult {
  /** @nullable */
  imageId?: string | null;
  /** @nullable */
  people?: PersonTraits[] | null;
  /** @nullable */
  warnings?: string[] | null;
}

export interface InventoryItem {
  createdAt?: string;
  modifiedAt?: string;
  /** @nullable */
  createdByUserId?: string | null;
  /** @nullable */
  modifiedByUserId?: string | null;
  /** @nullable */
  id?: string | null;
  /** @nullable */
  vendorId?: string | null;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  description?: string | null;
  traits?: GarmentTraits;
  price?: number;
  /** @nullable */
  currency?: string | null;
  /** @nullable */
  url?: string | null;
  /** @nullable */
  imageUrl?: string | null;
  inStock?: boolean;
}

export interface MeResponse {
  /** @nullable */
  userId?: string | null;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  provider?: string | null;
}

export interface PersonTraits {
  /** @nullable */
  personId?: string | null;
  /** @nullable */
  position?: string | null;
  /** @nullable */
  overallStyle?: string[] | null;
  /** @nullable */
  styleTags?: string[] | null;
  /** @nullable */
  clothingItems?: ClothingItemTraits[] | null;
  overallConfidence?: number;
  faceBoundingBox?: BoundingBox;
}

export interface ProblemDetails {
  /** @nullable */
  type?: string | null;
  /** @nullable */
  title?: string | null;
  /** @nullable */
  status?: number | null;
  /** @nullable */
  detail?: string | null;
  /** @nullable */
  instance?: string | null;
  [key: string]: unknown;
}

/**
 * @nullable
 */
export type ProfileResponseSeasonalSkew = {[key: string]: number} | null;

export interface ProfileResponse {
  /** @nullable */
  dominantStyles?: string[] | null;
  /** @nullable */
  colorPalette?: ColorWeight[] | null;
  formalityRange?: FormalityRange;
  /** @nullable */
  preferredFits?: string[] | null;
  /** @nullable */
  seasonalSkew?: ProfileResponseSeasonalSkew;
  /** @nullable */
  summary?: string | null;
  garmentCount?: number;
  createdAt?: string;
  modifiedAt?: string;
  /** @nullable */
  createdByUserId?: string | null;
  /** @nullable */
  modifiedByUserId?: string | null;
}

export interface RecommendRequest {
  /** @nullable */
  maxBudget?: number | null;
  /** @nullable */
  currency?: string | null;
  /** @nullable */
  categories?: GarmentCategory[] | null;
  /** @nullable */
  occasion?: string | null;
  count?: number;
}

export interface Recommendation {
  inventoryItem?: InventoryItem;
  score?: number;
  /** @nullable */
  reasoning?: string | null;
}

export interface RecommendationsResponse {
  /** @nullable */
  recommendations?: Recommendation[] | null;
  profileGeneratedAt?: string;
  requestedAt?: string;
}

export type Season = typeof Season[keyof typeof Season];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const Season = {
  spring: 'spring',
  summer: 'summer',
  fall: 'fall',
  winter: 'winter',
  all: 'all',
} as const;

export type GetApiGarmentsParams = {
category?: GarmentCategory;
page?: number;
pageSize?: number;
};

