/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Robe.AI — Wardrobe Style API
 * Garment trait extraction, wardrobe management, style profiling, and recommendations.
 * OpenAPI spec version: v1
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  ErrorResponse,
  ProblemDetails,
  RecommendRequest,
  RecommendationsResponse
} from '../generated-client.schemas';


type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;




/**
 * Requires a generated style profile. Returns items ranked by fit score,
filtered by optional budget, category, and occasion constraints.
 * @summary Get ranked recommendations based on the user's style profile and inventory.
 */
export const postApiUsersMeRecommendations = (
    recommendRequest: RecommendRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<RecommendationsResponse>> => {
    
    
    return axios.post(
      `/api/users/me/recommendations`,
      recommendRequest,options
    );
  }



export const getPostApiUsersMeRecommendationsMutationOptions = <TError = AxiosError<ErrorResponse | ProblemDetails>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiUsersMeRecommendations>>, TError,{data: RecommendRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof postApiUsersMeRecommendations>>, TError,{data: RecommendRequest}, TContext> => {

const mutationKey = ['postApiUsersMeRecommendations'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiUsersMeRecommendations>>, {data: RecommendRequest}> = (props) => {
          const {data} = props ?? {};

          return  postApiUsersMeRecommendations(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiUsersMeRecommendationsMutationResult = NonNullable<Awaited<ReturnType<typeof postApiUsersMeRecommendations>>>
    export type PostApiUsersMeRecommendationsMutationBody = RecommendRequest
    export type PostApiUsersMeRecommendationsMutationError = AxiosError<ErrorResponse | ProblemDetails>

    /**
 * @summary Get ranked recommendations based on the user's style profile and inventory.
 */
export const usePostApiUsersMeRecommendations = <TError = AxiosError<ErrorResponse | ProblemDetails>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiUsersMeRecommendations>>, TError,{data: RecommendRequest}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiUsersMeRecommendations>>,
        TError,
        {data: RecommendRequest},
        TContext
      > => {

      const mutationOptions = getPostApiUsersMeRecommendationsMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    