/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Robe.AI — Wardrobe Style API
 * Garment trait extraction, wardrobe management, style profiling, and recommendations.
 * OpenAPI spec version: v1
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  ProblemDetails,
  ProfileResponse
} from '../generated-client.schemas';


type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;




/**
 * @summary Generate or refresh the current user's style profile from their wardrobe.
 */
export const postApiUsersMeProfileGenerate = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ProfileResponse>> => {
    
    
    return axios.post(
      `/api/users/me/profile/generate`,undefined,options
    );
  }



export const getPostApiUsersMeProfileGenerateMutationOptions = <TError = AxiosError<ProblemDetails>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiUsersMeProfileGenerate>>, TError,void, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof postApiUsersMeProfileGenerate>>, TError,void, TContext> => {

const mutationKey = ['postApiUsersMeProfileGenerate'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiUsersMeProfileGenerate>>, void> = () => {
          

          return  postApiUsersMeProfileGenerate(axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiUsersMeProfileGenerateMutationResult = NonNullable<Awaited<ReturnType<typeof postApiUsersMeProfileGenerate>>>
    
    export type PostApiUsersMeProfileGenerateMutationError = AxiosError<ProblemDetails>

    /**
 * @summary Generate or refresh the current user's style profile from their wardrobe.
 */
export const usePostApiUsersMeProfileGenerate = <TError = AxiosError<ProblemDetails>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiUsersMeProfileGenerate>>, TError,void, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiUsersMeProfileGenerate>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getPostApiUsersMeProfileGenerateMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Get the current user's last generated style profile.
 */
export const getApiUsersMeProfile = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ProfileResponse>> => {
    
    
    return axios.get(
      `/api/users/me/profile`,options
    );
  }




export const getGetApiUsersMeProfileQueryKey = () => {
    return [
    `/api/users/me/profile`
    ] as const;
    }

    
export const getGetApiUsersMeProfileQueryOptions = <TData = Awaited<ReturnType<typeof getApiUsersMeProfile>>, TError = AxiosError<ProblemDetails>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiUsersMeProfile>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiUsersMeProfileQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiUsersMeProfile>>> = ({ signal }) => getApiUsersMeProfile({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiUsersMeProfile>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetApiUsersMeProfileQueryResult = NonNullable<Awaited<ReturnType<typeof getApiUsersMeProfile>>>
export type GetApiUsersMeProfileQueryError = AxiosError<ProblemDetails>


export function useGetApiUsersMeProfile<TData = Awaited<ReturnType<typeof getApiUsersMeProfile>>, TError = AxiosError<ProblemDetails>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiUsersMeProfile>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiUsersMeProfile>>,
          TError,
          Awaited<ReturnType<typeof getApiUsersMeProfile>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetApiUsersMeProfile<TData = Awaited<ReturnType<typeof getApiUsersMeProfile>>, TError = AxiosError<ProblemDetails>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiUsersMeProfile>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiUsersMeProfile>>,
          TError,
          Awaited<ReturnType<typeof getApiUsersMeProfile>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetApiUsersMeProfile<TData = Awaited<ReturnType<typeof getApiUsersMeProfile>>, TError = AxiosError<ProblemDetails>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiUsersMeProfile>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary Get the current user's last generated style profile.
 */

export function useGetApiUsersMeProfile<TData = Awaited<ReturnType<typeof getApiUsersMeProfile>>, TError = AxiosError<ProblemDetails>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiUsersMeProfile>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetApiUsersMeProfileQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




